### PR TITLE
Implement a C++ macro generator to ingest ES6 IDL and generate a node hierachy

### PR DESCRIPTION
**Pull request by acomminos**
Hackishly generates a set of defines to be used to express the relationship between IDL nodes and their models. `model_id` included to help a decoder deduplicate any models for a given field.

### CODE REVIEW

**Comment by Yoric** [comment]
If there's any interest, I have a much more comprehensive set of macros generated from the IDL in the Firefox parser generator.

**Comment by dominiccooney** [comment]
Is this still up-to-date? Could we add something to the test script which runs this and checks that a C++ frontend doesn't choke on the output?

**Comment by Yoric** [comment]
What is the use case of this generator?

As mentioned above, the Firefox parser generator generates a much more comprehensive set of macros, which is tested by the Firefox build system, so if we could avoid fragmentation, that would probably be for the best.

[This is what the result looks like](https://searchfox.org/mozilla-central/source/js/src/frontend/BinASTToken.h).

**Comment by acomminos** [comment]
Happy to drop this in favour of the FF macros, this was intended to get a scrappy V2 decoder in C++ up and running.

**Comment by dominiccooney** [comment]
Thanks Andrew. Context for Yoric, Andrew and I were kicking around ideas for a simple decoder, this probably isn't of interest.

**Pull request closed without merging**
